# Generated by Django 3.2.7 on 2021-09-18 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 18, 13, 43, 37, 960981, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
