# Generated by Django 3.2.7 on 2021-10-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Khalti', 'Khalti'), ('Esewa', 'Esewa')], default='Cash on Delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Refunded', 'Refunded')], default='created', max_length=120),
        ),
    ]
